### ISSUE TITLE
Syntax error running blech_clust_pre.sh

### ISSUE THREAD

**Issue by natashakbt** [abuzarmahmood/blech_clust#158]
Encountered error while running blech_clust_pre.sh. Message:

Running Jetstream Bash
blech_clust_pre.sh: line 8: syntax error: unexpected end of file

**Comment by abuzarmahmood** [comment]
Could you tell me what commit you're on? Please just paste the output of `git log -1` when you're in the blech_clust folder

**Comment by natashakbt** [comment]
commit ab2835e9db5a51a8a6e6e1c7525eebbe087e4bd9 (HEAD -> fix_digin_numbering, origin/fix_digin_numbering)
Author: abuzarmahmood <abuzarmahmood@gmail.com>
Date:   Mon Oct 16 13:00:38 2023 -0400

    Fix plotting lims for segmentation plot

**Comment by natashakbt** [comment]
Last few lines of output
"""
Running Common Average Reference
Processing : /media/natasha/drive2/Natasha_Data/NB33/NB33_test1_3tastes_240308_131055/
 Number of groups : 1
 GC :: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31]
Calculating common average reference for 1 groups
Calculating mean values
Processing Group 0
100%|██████████████████████████████████████████████████████████████████████████████| 30/30 [01:09<00:00,  2.30s/it]
Common average reference for 1 groups calculated
Performing background subtraction
0it [00:00, ?it/s]Processing group GC
100%|██████████████████████████████████████████████████████████████████████████████| 30/30 [00:58<00:00,  1.95s/it]
1it [00:58, 58.41s/it]█████████████████████████████████████████████████████████████| 30/30 [00:58<00:00,  2.48s/it]
Modified electrode arrays written to HDF5 file after subtracting the common average reference
Running Jetstream Bash
blech_clust_pre.sh: line 8: syntax error: unexpected end of file

**Comment by abuzarmahmood** [comment]
This is a known issue with this commit. 
Please remove the `&&` in the last line of the file (code shown below) and it should work.
Or please update to at least commit 11bb6f9, however, the update will involve major changes in functionality

```
DIR=$1
echo Running Blech Clust 
python blech_clust.py $DIR &&
echo Running Common Average Reference 
python blech_common_avg_reference.py $DIR &&
echo Running Jetstream Bash 
for x in $(seq 10);do bash blech_run_process.sh $DIR;done &&
```

**Comment by natashakbt** [comment]
Updated code as suggested, now getting new error

```
Running Jetstream Bash
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
bash: blech_run_process.sh: No such file or directory
```

**Comment by abuzarmahmood** [comment]
It seems like there was a bit of a snafu with that commit and `blech_run_process` wasn't actually included in the merge.
If you update to 122ec173f66cd0ca7374f59cadaa3984639987d0 (just 2 commits later), that should fix the issue without any changes in functionality.

**Comment by natashakbt** [comment]
That seems to have fixed the issue.

**Comment by abuzarmahmood** [comment]
Closing issue. Please reopen if any further issues arise.
