### ISSUE TITLE
Issue running blech_clust_run

### ISSUE THREAD

**Issue by cmazzio** [abuzarmahmood/blech_clust#162]
Something wrong with clustermap...block below

https://app.warp.dev/block/dCgZKFhhjbhMucPFLNzCO6

**Comment by abuzarmahmood** [comment]
On this commit (431ceb9), `cluster_stability.py` is outputting to cluster folders with zero-padded numbers

https://github.com/abuzarmahmood/blech_clust/blob/431ceb95d1bc431c20cb4f1c5e6b49f00936ca35/utils/cluster_stability.py#L135C1-L138C13
```
        fig.savefig(f'./Plots/{electrode_num:02}/clusters{clust_num:02}/' +\
                        f'clustermap.png', dpi=300,
                         bbox_inches='tight')
        plt.close()
```

but `blech_run_process.py` creates the directories without zero-padding (see `f'clusters{self.cluster_num}'` below)

https://github.com/abuzarmahmood/blech_clust/blob/431ceb95d1bc431c20cb4f1c5e6b49f00936ca35/utils/blech_process_utils.py#L232C1-L237C10

```
        clust_results_dir = os.path.join(
            self.data_dir,
            'clustering_results',
            f'electrode{self.electrode_num:02}',
            f'clusters{self.cluster_num}'
        )
```

You can remove the zero padding for the cluster directory in `cluster_stability.py` and it should work.

**Comment by cmazzio** [comment]
That fixed the issue.
