### ISSUE TITLE
agg backend used for blech_post_process

### ISSUE THREAD

**Issue by Mraymon5** [abuzarmahmood/blech_clust#191]
/home/ramartin/blech_clust-180-issues-with-blech_processpy/utils/blech_post_process_utils.py:164: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

**Comment by Mraymon5** [comment]
We identified that the culprit here was `blech_process_utils.py`, line 21:
`matplotlib.use('Agg')`

Commenting out that line allowed `blech_post_process.py` to run normally.

I was considering running through the code and eliminating, or at least commenting out, uses of `Agg`, but discussed it with ChatGPT first, given that I have no idea what `Agg` is. It seems like running `matplotlib` with `agg` is useful in situations where you don't need real-time user interaction with the plots, so the plot can just be saved rather than displayed. ChatGPT points out that this is primarily useful for situations where people are running code without a monitor (a situation that I don't think is really relevant to us), or for automated scripts that just need to save figures without displaying them (which I think is potentially actually relevant).

I still don't totally understand the benefit of `agg` to the automated scripts, so given my lack of understanding, I'm going to hold off on proposing any changes.

**Comment by abuzarmahmood** [comment]
My knee-jerk reaction is that we can take it out, run through the pipeline, and see what happens.
From my understanding, it's supposed to prevent the datashader plots from showing during the generation process...BUT, I am willing to bet that it showing up in `blech_process_utils.py` is accidental.

**Comment by abuzarmahmood** [comment]
HOTFIX applied. Please reopen issue if problem persists
