### ISSUE TITLE
Quality control scipt/directory

### ISSUE THREAD

**Issue by abuzarmahmood** [abuzarmahmood/blech_clust#21]
Includes:
1. Unit similarity check
2. Unit drift check (ANOVA for spike count over time) #16 
 
**Ignore ones below...not sure if they can be counted as quality assurance**
3. Population dynamicity check (relative to other recorded populations)
4. Number + Fraction of taste responsive + discriminative + palatability encoding neurons

**Comment by jianyoulin** [comment]
Plot to visualize activity of all sorted neurons across session

**Comment by abuzarmahmood** [comment]
Of course :) Thank you for discussing this with me the other day. This
should be a useful addition.

Postdoctoral Researcher | Katz Lab <https://katzlab.squarespace.com/>
Volen Center for Complex Systems
Brandeis University
Website <https://abuzarmahmood.github.io/> | LinkedIn
<https://www.linkedin.com/in/abuzarmahmood/>

**Comment by jianyoulin** [comment]
Thank YOU... Talking to you is my evoked dopamine rise time....
