### ISSUE TITLE
Install Readme Update

### ISSUE THREAD

**Issue by hfgem** [abuzarmahmood/blech_clust#47]
`pip install -r pip_requirements.txt                 # Install pip requirements (not covered by conda)`
should be changed to
`pip install -r pip_requirements_base.txt                 # Install pip requirements (not covered by conda)`

**Comment by abuzarmahmood** [comment]
Done [e085de8](https://github.com/abuzarmahmood/blech_clust/commit/e085de873e40ddae07932b1f53b9d17227edf4d4)
